apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: joanie
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - environment: staging
        imageTag: staging
      - environment: preprod
        imageTag: main
  template:
    metadata:
      name: joanie-{{ environment }}
      annotations:
        argocd-image-updater.argoproj.io/image-list: rouaidaka/joanie:{{ imageTag }}
    spec:
      project: default
      source:
        repoURL: https://github.com/rouaidakacem/GitOps-with-ArgoCD.git
        targetRevision: HEAD
        path: joanie
        helm:
          valueFiles:
            - ../values/{{ environment }}.yaml
          parameters:
          - name: image.repository
            value: rouaidaka/joanie
          - name: image.tag
            value: "{{ imageTag }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: joanie-{{ environment }}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true  