apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    secret: AgCr0Ga/MHdzPEcAYnA/CpaC+H58OJe3XWYcIdfpbhwgWGIGPKKc7JMzqdcQWRQyCTGnABDSmsPBiM8+YXBFGEkxW6v9WSWxZKajFA+3OqKdIuK6kXslQvB5CWEXjmqTuPxnR1mdpe9Rf3/7lKummtUkSSKpeXv4EEfWifJuvjnN+or2lUjr3d+u8pw/1nvlhTa8+2V7JcL30tIpIimFEMetgrUm8U1cHZDsrUw0d/g/+6PWjXe4PJpNjHmA99eVIoQ0iZBgqM1J5BicMp9dw9VCt7GLlBnz6/ntnV42MI6TCq8jNggwX4upsCu+lOFQsQla+5jr41nhXwv3ZWAinJ4W/PaByhmZWusrpfrVUzLkaebHNt5TVXlehR98ka9YpkFcN+QvSHVsLPRO7lzUbihEHR2AsqK6Kt+O8eSwCf6T/U9JZ9URd6UpguAMsoGEEbOiGlIZMhWBT/ks1GF2TZGIY+IkbSY10RYIHO1J5QXntiLpOW74jk/R5VUV24I4KGS/TuN+YGqgGJk8aJ5qwZYXWQJxyLGo2s+/JBX0SZTRIJd7t17eabdSqTD3IGAyvg6ljFop6vYv0bISzr+8ea1FdYoP8EOnngUxZMZN6ns0FR3OsOslQ+iDoAYOeYvmqOCsVS517jMdRIWLNfH9g5EtaboglmtB2NV5qLKswVq+xuXzVwUdQDA5w9xykacc/EwqH7nKoTj7FPMds6lQWKffufLvnaHE6sl3Ktc5xkikxXA/7xr5zFmRc1E/f3ZfnLhzvfvvQzqQnh0V6p5R7xR6olDW7rMAdUt4yY76HzFa+bCzG/8InjvnjOwwl0Kk+ATRmFEJfMt4CJO5rTeshosTnmFeS0nbc0BTxIeAgS9N5Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

